project:
  type: book
lang: de-DE
texplate:
  deadline: 31.7.2023
  supervisor: Prof. Dr. Jean Dupont
  location: Köln

book:
  title: "Erschließung eines Netzwerks von Named Entities aus Nachrichtenartikeln am Beispiel von www.tagesschau.de"
  author: 
    - name: Patrick Haas
      orcid: 0000-0003-3479-6572
      corresponding: true
      email: p@trickhaas.de
      affiliation: FOM Hochschule für Oekonomie & Management
      note: 311431
    - name: Martin Helmke
      orcid: 0000-0003-3479-6572
      attributes:
        matrikel: "311431"
      corresponding: true
      email: p@trickhaas.de
      affiliation: FOM Hochschule für Oekonomie & Management
      note: 311431
    - name: Benjamin Raska
      orcid: 0000-0003-3479-6572
      matrikel: 311431
      corresponding: true
      email: p@trickhaas.de
      affiliation: FOM Hochschule für Oekonomie & Management
      note: 311431

  date: last-updated
  chapters:
    - index.qmd
    - references.qmd

keywords:
  - Entity Linking
  - Network Science
abstract: |
  In September 2021, a significant jump in seismic activity on the island of La Palma (Canary Islands, Spain) signaled the start of a volcanic crisis that still continues at the time of writing. Earthquake data is continually collected and published by the Instituto Geográphico Nacional (IGN). ...
plain-language-summary: |
  Earthquake data for the island of La Palma from the September 2021 eruption is found ...
key-points:
  - A web scraping script was developed to pull data from the Instituto Geogràphico Nacional into a machine-readable form for analysis
  - Earthquake events on La Palma are consistent with the presence of both mantle and crustal reservoirs.
date: last-modified
citation:
  container-title: Earth and Space Science
number-sections: true

bibliography: references.bib

format:
  html:
    theme: yeti
  fom-pdf:
    latex-output-dir: out
    latex-clean: true
    keep-tex: true
